export const APP_SHOW_MESSAGE = 'APP_SHOW_MESSAGE';
export const APP_CLEAR_MESSAGE = 'APP_CLEAR_MESSAGE';
export const APP_REQUEST = 'APP_REQUEST';
export const APP_REQUEST_END = 'APP_REQUEST_END';

export const USER_CLEAR = 'USER_CLEAR';
export const USER_RECEIVE = 'USER_RECEIVE';

export const OBJECTS_SELECT = 'OBJECTS_SELECT';
export const OBJECTS_REMOVE = 'OBJECTS_REMOVE';
export const OBJECTS_REQUEST = 'OBJECTS_REQUEST';
export const OBJECTS_RECEIVE = 'OBJECTS_RECEIVE';
export const OBJECTS_RECEIVE_PARAMS = 'OBJECTS_RECEIVE_PARAMS';

export const STATISTICS_REQUEST = 'STATISTICS_REQUEST';
export const STATISTICS_RECEIVE = 'STATISTICS_RECEIVE';

export const CRASHES_REQUEST = 'CRASHES_REQUEST';
export const CRASHES_RECEIVE = 'CRASHES_RECEIVE';
